name: Check Application State

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Health Check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://thawing-everglades-99553.herokuapp.com/health
          follow-redirect: false
          max-attempts: 2
          retry-delay: 5s
          retry-all: false
