name: Check Application State

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  healthcheck:
    uses: jtalk/url-health-check-action@v2
    with:
      url: https://thawing-everglades-99553.herokuapp.com
      follow-redirect: false
      max-attempts: 2
      retry-delay: 5s
      retry-all: false
